### ISSUE TITLE
More detailed usage for a newbee

### ISSUE THREAD

**Issue by joustava** [jjcarstens/dht#6]
With the original repo from which this is forked https://github.com/jjcarstens/nerves_dht -> https://github.com/esdrasedu/nerves_dht

I am able to make it work like
```elixir
iex(7)> defmodule MyGenServer do
...(7)>          use NervesDht
...(7)>        end
{:module, MyGenServer,
 <<70, 79, 82, 49, 0, 0, 20, 252, 66, 69, 65, 77, 65, 116, 85, 56, 0, 0, 2, 31,
   0, 0, 0, 56, 18, 69, 108, 105, 120, 105, 114, 46, 77, 121, 71, 101, 110, 83,
   101, 114, 118, 101, 114, 8, 95, 95, 105, ...>>, :ok}
iex(8)> {:ok, dht} = MyGenServer.start_link({23, 11})
{:ok, #PID<0.1182.0>}
iex(9)> {:ok, humidity, temperature} = MyGenServer.info(dht)
{:ok, 33.0, 22.0}
```
As described in https://github.com/esdrasedu/nerves_dht/blob/master/lib/nerves_dht.ex.

Does this library need a similar approach? 

Simply running 
```elixir
iex(2)> DHT.read(23, :dht11)
** (exit) exited in: GenServer.call(DHT.Port, {:read, 23, 11}, 5000)
    ** (EXIT) an exception was raised:
        ** (FunctionClauseError) no function clause matching in DHT.Port.handle_info/2
            (dht 0.1.1) lib/dht/port.ex:33: DHT.Port.handle_info({#Port<0.123>, {:exit_status, 1}}, %{port: #Port<0.123>})
            (stdlib 3.15.2) gen_server.erl:695: :gen_server.try_dispatch/4
            (stdlib 3.15.2) gen_server.erl:771: :gen_server.handle_msg/6
            (stdlib 3.15.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
    (elixir 1.12.2) lib/gen_server.ex:1024: GenServer.call/3
iex(2)> ** (EXIT) interrupted
```
Doesn't seem to go well, I must be forgetting something as a newbee to Elixir and Nerves.
I'm using an rpi2.

**Comment by jjcarstens** [comment]
You are using as expected. The issue here is that the port is crashing when trying to read (which should prob be handled?) If you have more log input from the crash, that might be useful. Otherwise it might be a bit before I am able to dig into this further.

You could also try `DHT.start_polling/3` to see if you get the same results or if reads start coming through. 

The DHT is very finicky on how often you can read from it which might be what is crashing the port. The DHT11 is also even more sensitive.

**Comment by dkuku** [comment]
I got the exactly same problem with two different dht11. I tried different approaches including pooling, and after finding this thread I managed to get it working with the other lib without any problems.

**Comment by joustava** [comment]
@jjcarstens Thanks for the reply, I don't have to doubt myself at least. :)

> You are using as expected. The issue here is that the port is crashing when trying to read (which should prob be handled?) If you have more log input from the crash, that might be useful. Otherwise it might be a bit before I am able to dig into this further.

Meaning, my code should handle the crash or this lib? Could it be that the port has been opened and opening it again would crash it? I will have a look at it again soonish.

**Comment by jjcarstens** [comment]
@joustava No, you don't need to handle the crash. This lib should prob handle it.

Can you tell me what version of Elixir/Nerves you're using (`elixir -v && mix nerves.env --info`)? I'm pretty sure I might know whats going on...

**Comment by jjcarstens** [comment]
Actually, I confirmed that is the error and made a fix in the PR above.

@joustava & @dkuku Can you test again with `v0.1.2`?

**Comment by joustava** [comment]
Yup, had
```
Erlang/OTP 24 [erts-12.0.3] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit]

Elixir 1.12.2 (compiled with Erlang/OTP 24)
```

After updating the version:

```
iex(4)> top
Press enter to stop

Total processes: 199
Application  Name or PID                   Reds/Δ      Mbox/Δ     Total/Δ      Heap/Δ     Stack/Δ
...
dht          Pollers.PIDPartition0           77/1         0/0       233/0       233/0        12/0
dht          Pollers                        445/1         0/0       986/0       610/0        12/0
dht          DHT.Telemetry                  113/1         0/0       233/0       233/0        12/0
dht          DHT.Port                       225/1         0/0       233/0       233/0        12/0
dht          DHT.Supervisor                 919/1         0/0      1597/0       987/0        12/0
dht          <0.1099.0>                     160/1         0/0       233/0       233/0         7/0
dht          <0.1098.0>=application_maste    78/1         0/0       233/0       233/0         8/0
...
iex(5)> DHT.read(23, :dht11)
{:ok, %{humidity: 31.0, temperature: 21.0}}
iex(6)>
```

Now it works again as described and I'll use this one. Thanks for fixing!
